### ISSUE TITLE
Rework using leaflet plugin

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-frontend-legacy#51]
We should drop most of the control code in favor of using:

https://github.com/perliedman/leaflet-routing-machine

Todo:
- [x] Check feature difference
- [x] Determine what of the missing features we _really_ need
- [x] Include as submodule
- [x] Implement missing features

@DennisOSRM

**Comment by DennisOSRM** [comment]
Great idea. Talked to a three people about the leaflet plugin in the last two days. Everyone likes it. 

Let's JFDI!

**Comment by TheMarex** [comment]
Things that are missing from LRM that we need:
-  No 'dragging marker' support
-  Adding start/end markers by clicking on the map: https://github.com/perliedman/leaflet-routing-machine/issues/4
-  i18n: https://github.com/perliedman/leaflet-routing-machine/issues/10

Less important:
-  QRCodes ?
-  Printing
-  GPX export
-  Mapping tools

The first 2 points are clear blockers. i18n is important but personally I could (initially) live without it.
The other stuff can be added post-launch if needed.

Proposed strategy:
- [ ] Create frontend with missing features
- [ ] Add dragging marker support and bring it upstream
- [ ] Add adding markers by click and bring it upstream

It seems to be clear that is will actually be a clean rewrite rather than an incremental update. Should we consider creating a new repository for this, rather than a branch?

**Comment by DennisOSRM** [comment]
Let's do it in a branch. Initially it can lack features, but we would release it once it has feature parity.

**Comment by emiltin** [comment]
If you do a rewrite of the front-end, have you considered using backbone or similar? This is what we use at www.ibikecph.dk (as part of a Rails app): https://github.com/ibikecph/ibikecphsite/tree/master/app/assets/javascripts

**Comment by DennisSchiefer** [comment]
Some more (minor) things that are missing/erroneous with LRM:
- jsonp management when facing slow/no server responses
- snapping of markers to itineraries
- behaviour when crossing the +-180° longitude line

If this is done as a new branch, how is it later turned into the new master/develop branch once feature parity is reached (I assume merging is not an option) ?

**Comment by DennisOSRM** [comment]
Good points.

We should coordinate a bit. How about doing a hangout conference call on Monday? Does 5pm CET (1 pm ET) work for everyone.

**Comment by TheMarex** [comment]
Should work for me. @perliedman want to join as well?

**Comment by DennisOSRM** [comment]
@perliedman would be awesome if you could join, too.

**Comment by DennisSchiefer** [comment]
I have a meeting at 5:30pm CET, which will probably take about an hour.

**Comment by DennisOSRM** [comment]
@dennisschiefer would 30 mins earlier work for you?

**Comment by perliedman** [comment]
Hi guys, sounds really great!

I would most likely be able to join on monday.

Some quick notes on your discussion above:
- Not entirely sure what you mean by "draggable markers", but dragging waypoint markers is definitely supported
- Also, not sure, but if "snapping markers to itinerary" means visualizing itinerary steps on the map, this _is_ supported, although it isn't deployed on the demo site (http://www.liedman.net/leaflet-routing-machine/); the other way around isn't currently supported, though (hovering the route on the map to see which step in the itinerary it corresponds to)
- Crude i18n support is also possible when using latest master, by overriding the supplying your own `L.Routing.Formatter` instance. We might want to improve this support, though.

It might also be worth noting that the plugin is designed to be possible to customize; an example is http://www.trafiken.nu/goteborg/Cykel/Cykelreseplanerare/ (sorry, only in swedish, but you might be able to guess how it works) - this is built upon LRM, but with a lot of custom interaction. This might be interesting for some things that could be specific for OSRM's web site.

Anyway, I'm happy to try to help as much as possible with this (although my free time is a bit limited). It would be great to see the plugin deployed in production outside Sweden :grinning:.

**Comment by TheMarex** [comment]
@perliedman there is are special API parameters in OSRM that will generate a route faster, if you click on a marker and drag it. LRM only recomputes the route when you let go of the marker. Check out the demo site: http://map.project-osrm.org
Create a route, start dragging a marker and you can see that the route is recomputed while dragging.

> It might also be worth noting that the plugin is designed to be possible to customize [...]

That is exactly the reason why we chose it. :-)

**Comment by DennisSchiefer** [comment]
@DennisOSRM 30 minutes earlier would work

**Comment by perliedman** [comment]
@TheMarex ok, did not know that. Sounds cool and would be a really nice addition.

**Comment by DennisOSRM** [comment]
Ok. Then lets do 4:30 pm CET (10:30 am ET) if there are no objections.

**Comment by perliedman** [comment]
I need some info on how to join the hangout... I'm assuming we're talking Google Hangout, right?

**Comment by DennisOSRM** [comment]
Yep, Google Hangout. I'll post a link here a couple of minutes prior.

**Comment by DennisOSRM** [comment]
Hangout link: ~~hxxps://plus.google.com/hangouts/_/gyt437lwye3sj524tkpbnknmyaa~~

**Comment by DennisOSRM** [comment]
Thanks for the good discussion, everyone. Here's the summary of what we discussed:

OSRM frontend:
-  use as few code as possible to glue several leaflet plugins into a new (maintainable) frontend
- QRcode not terribly important, but should be easy to integrate.
- For now pull in plugins as copies instead of things like browserify

LRM:
- JSONP request should have a timestamp to account for data races.
- Dateline may be an issue: Server does not responds to longitudes leaving (-180/+180).
- Snapping markers onto the route to origin/destination/via locations
  - perhaps a dashed line from marker locations to start of route

We have a new mile stone in here called 'Frontend V2' and a new repository: https://github.com/Project-OSRM/osrm-frontend-v2

**Comment by DennisOSRM** [comment]
@TheMarex Can you run point on adding tickets to the LRM repo and link them back here?

**Comment by TheMarex** [comment]
Now tracking in:

# LRM
- [x] [Snapping markers](https://github.com/perliedman/leaflet-routing-machine/issues/37)
- [x] [Adding timeouts + timestamps](https://github.com/perliedman/leaflet-routing-machine/issues/36)
- [x] [Adding i18n](https://github.com/perliedman/leaflet-routing-machine/issues/10)

# OSRM frontend
- [ ] [QRcode related code into own leaflet plugin](https://github.com/Project-OSRM/osrm-frontend/issues/52)

# OSRM frontend v2
- [x] Push initial version
- [x] Integrate new style

# OSRM backend
- [ ] [Dateline issue](https://github.com/Project-OSRM/osrm-backend/issues/1188)

**Comment by TheMarex** [comment]
This shipped.

**Comment by perliedman** [comment]
Wow, this is great news! Nice work by everyone involved. :confetti_ball:
