### ISSUE TITLE
Move QR-Code to own leaflet plugin

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-frontend-legacy#52]
The [QR-Related code](https://github.com/Project-OSRM/osrm-frontend/tree/master/WebContent/qrcodes) seems general enough to be a small leaflet plugin. But we should check first for an existing implementation.

**Comment by DennisOSRM** [comment]
There is probably no existing plugin. The QRcode stuff is pretty orthogonal to what leaflet does. We use it only to encode the URL of a short link.

**Comment by TheMarex** [comment]
This got dropped.
