### ISSUE TITLE
[Question] Route instruction

### ISSUE THREAD

**Issue by trofimchyk** [Project-OSRM/osrm-frontend-legacy#54]
Hi.
Sorry for a maybe stupid question but could you please explain what does [this](https://github.com/Project-OSRM/osrm-frontend/blob/master/WebContent/localization/OSRM.Locale.en.js#L121) instruction means?
What I need to show to the end user?
Thank you.

**Comment by DennisSchiefer** [comment]
It's usually the first driving instruction and gives the user the cardinal direction in which to move (e.g. "Head North onto Main Street")

**Comment by trofimchyk** [comment]
@DennisSchiefer Thank you for fast answering!
