### ISSUE TITLE
Tilesets missing

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-frontend-legacy#55]
The first 4 tile layers shown on the demo site at http://map.project-osrm.org/:

OSRM bright
Mapbox Terrain
Mapbox Labelled Satellite
Mapbox Satellite

are no longer showing.  All 4 are Mapbox tilesets, it looks like they're no longer available.

**Comment by DennisOSRM** [comment]
We'll push an update later today

**Comment by DennisOSRM** [comment]
pushed. switched to osm.org as the default layer
